/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DutschAuction__factory } from "./DutschAuction__factory";
export { ERC20Token__factory } from "./ERC20Token__factory";
